keys:
  - &host_ssh age1w0uhfv6cghqducechtaajzeqeycpyu6hed3sr6qe97kj5hla092qxuhetz

creation_rules:
  - path_regex: (secrets\.yaml|pc\.sops\.conf)$
    key_groups:
      - pgp: []
        age:
          - *host_ssh
